version: '3.1'
services:
  stats-server:
    build: stats-service/server
    image: ewm-stats-service-image
    container_name: ewm-stats-service
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm-stats-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=P@ssw0rd
    restart: on-failure

  stats-db:
    image: postgres:14-alpine
    container_name: ewm-stats-db
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ewm-stats-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=P@ssw0rd
      - TZ=Europe/Moscow
    restart: on-failure

  ewm-service:
    build: main-service
    image: ewm-main-service-image
    container_name: ewm-main-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=P@ssw0rd
    restart: on-failure


  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-db
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=ewm-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=P@ssw0rd
      - TZ=Europe/Moscow
    restart: on-failure
